export const MY_API_URI = 'https://www.averlist.xyz/api'
export const MY_AVATAR_URI = 'https://www.averlist.xyz/api/users/me/avatar/'
export const MY_PICTURE_URI = 'http://www.averlist.xyz/api/news/picture/'
// export const MY_API_URI = 'http://localhost:8080'
// export const MY_AVATAR_URI = 'http://localhost:8080/users/me/avatar/'
// export const MY_PICTURE_URI = 'http://localhost:8080/news/picture/'

// export const ANILIBRIA_API_URI = 'https://api.anilibria.tv/v2'
export const ANILIBRIA_API_URI = 'https://api.sdev.xyz/v2'
export const ANILIBRIA_URI = 'https://dl-20211030-963.anilib.top/'
