export interface ThemeVariables {
	[key: string]: string
	'antd-header-background-color': string
	'antd-menu-background-color': string
	'antd-menu-background-hover-color': string
	'antd-menu-border-color': string
	'antd-breadcrumb-text-color': string
	'antd-breadcrumb-text-hover-color': string
	'antd-textarea-background-color': string
	'antd-textarea-border-color': string
	'antd-textarea-border-hover-color': string
	'antd-textarea-box-shadow-focus-color': string
	'antd-input-background-color': string
	'antd-input-border-color': string
	'antd-input-border-hover-color': string
	'antd-input-box-shadow-focus-color': string
	'antd-autocomplete-background-color': string
	'antd-autocomplete-border-color': string
	'antd-autocomplete-border-hover-color': string
	'antd-autocomplete-box-shadow-focus-color': string
	'antd-select-background-color': string
	'antd-select-border-color': string
	'antd-select-border-hover-color': string
	'antd-select-box-shadow-focus-color': string
	'antd-select-arrow-color': string
	'antd-message-background-color': string
	'antd-button-brightness-coefficient': string
	'antd-table-thead-background-color': string
	'antd-table-thead-background-hover-color': string
	'antd-table-tbody-background-color': string
	'antd-table-tbody-border-color': string
	'antd-table-tbody-row-background-hover-color': string
	'antd-modal-background-color': string
	'antd-modal-border-color': string
	'antd-checkbox-background-color': string
	'antd-checkbox-border-color': string
	'antd-accordion-background-color': string
	'antd-accordion-border-color': string
	'antd-description-border-color': string
	'antd-description-label-background-color': string
	'antd-icon-color': string
	'header-background-color': string
	'hamburger-background-color': string
	'hamburger-button-color': string
	'main-background-color': string
	'anilibria-loader-color': string
	'user-component-background-color': string
	'dialog-component-background-color': string
	'chat-background-color': string
	'body-scrollbar-thumb-color': string
	'text-color': string
	'friends-footer-background-color': string
}
